* Crate release
- Release ~perf-event-open-sys~
  - [ ] Ensure that all issues in the GitHub "Next `sys` release"
    milestone are closed.
  - [ ] Run the command:

    #+BEGIN_SRC sh
    cd perf-event-open-sys && cargo semver-checks
    #+END_SRC

    See the notes in ~perf-event-open-sys/README.md~ for advice on how
    to interpret the results.

  - [ ] If there are semver-incompatible changes to the API, make a new major release.
    - [ ] Check for a new release of ~bindgen~. If there is a new one
      that has been out for two weeks, install it and regenerate the
      bindings. Bindgen may introduce semver-incompatible changes, so
      unless we know of important bugs in the current bindings, it's
      best only to upgrade bindgen when Linux has forced us to make a
      new major release anyway.
  - [ ] Assign the crate a new version number ,as directed by above. Update in:
    - [ ] ~perf-event-open-sys/Cargo.toml~
    - [ ] ~perf-event/Cargo.toml~ as dependency
  - [ ] Run: ~cargo fmt~
  - [ ] Run: ~cargo clippy --workspace --tests~
  - [ ] Run: ~cargo test --workspace~
  - [ ] Update ~perf-event-open-sys/RELEASE-NOTES.md~.
  - [ ] Publish the crate:
    - [ ] ~cargo publish -p perf-event-open-sys --dry-run~
    - [ ] ~cargo publish -p perf-event-open-sys~
  - [ ] Create a new tag called ~perf-event-open-sys-vX.Y.Z~, and push it to the repo.
- Release ~perf-event~
  - [ ] Ensure that all issues in the GitHub "Next `perf-event` release"
    milestone are closed.
  - [ ] Run the command:

    #+BEGIN_SRC sh
    cd perf-event && cargo semver-checks
    #+END_SRC

    See notes above about ~cargo semver-checks~.

  - [ ] Assign the crate a new version number ,as directed by above. Update in:
    - [ ] ~perf-event/Cargo.toml~
  - [ ] Run: ~cargo fmt~
  - [ ] Run: ~cargo clippy --workspace --tests~
  - [ ] Run: ~cargo test --workspace~
  - [ ] Publish the crate:
    - [ ] ~cargo publish -p perf-event --dry-run~
    - [ ] ~cargo publish -p perf-event-open-sys~
  - [ ] Create a new tag called ~perf-event-vX.Y.Z~, and push it to the repo.
* Generate bindings for a new Linux kernel version
- [ ] Ensure you are using the same version of ~bindgen~ that was used
  to generate the extant bindings. The bindgen version is recorded in the
  header comments in the ~bindings_ARCH.rs~ files.

  Switching to a new ~bindgen~ version should always be its own
  commit, separate from updating the Linux version, since new
  ~bindgen~ versions can sometimes introduce semver-incompatible
  changes.
- [ ] In ~perf-event-open-sys/regenerate.sh~, update ~version~ to the
  desired Linux kernel version. You don't need to download the sources
  yourself; the script fetches them, and caches them in the ~target~
  directory.
- [ ] From any directory, run the ~regenerate.sh~ script. This fetches
  the kernel sources if necessary, runs bindgen, and generates the
  ~bindings_ARCH.rs~ files.
- [ ] ~cargo test --workspace~
- [ ] Look at the diff, and update  ~perf-event-open-sys/RELEASE-NOTES.md~
  to cover any new ~perf_event_open~ API features.
- [ ] Consider releasing a new version of the ~perf-event-open-sys~
  crate; see checklist above.
