* Crate release
** ~perf-event-open-sys~
- [ ] Check for a new release of `bindgen`. If there is a new one that
  has been out for two weeks, install it and regenerate the bindings.
- [ ] Run the command:

  #+BEGIN_SRC sh
  cd perf-event-open-sys && cargo semver-checks
  #+END_SRC

  See the notes in ~perf-event-open-sys/README.md~ for advice on how
  to interpret the results.

- [ ] new version number (as directed by above)
  - [ ] ~perf-event-open-sys/Cargo.toml~
  - [ ] ~perf-event/Cargo.toml~ as dependency
- [ ] ~cargo fmt~
- [ ] ~cargo clippy --workspace --tests~
- [ ] ~cargo test --workspace~
- [ ] Update ~perf-event-open-sys/RELEASE-NOTES.md~.
- [ ] ~cargo publish -p perf-event-open-sys --dry-run~
- [ ] ~cargo publish -p perf-event-open-sys~
- [ ] Create a new tag called `perf-event-open-sys-vX.Y.Z` and push it to the repo.
** ~perf-event~
- [ ] Run the command:

  #+BEGIN_SRC sh
  cd perf-event && cargo semver-checks
  #+END_SRC

  See notes above about ~cargo semver-checks~.

- [ ] new version number (as directed by above)
  - [ ] ~perf-event/Cargo.toml~
- [ ] ~cargo fmt~
- [ ] ~cargo clippy --workspace --tests~
- [ ] ~cargo test --workspace~
- [ ] ~cargo publish -p perf-event --dry-run~
- [ ] ~cargo publish -p perf-event-open-sys~
- [ ] Create a new tag called `perf-event-vX.Y.Z` and push it to the repo.
* Generate bindings for a new Linux kernel version
- [ ] Check for a new release of `bindgen`. If there is a new one that
  has been out for two weeks, install it and regenerate the bindings.
- [ ] In ~perf-event-open-sys/regenerate.sh~, update ~version~ to the
  desired Linux kernel version. You don't need to download the sources
  yourself; the script fetches them, and caches them in the ~target~
  directory.
- [ ] Run the command:

  #+BEGIN_SRC
  cd perf-event-open-sys && ./regenerate.sh
  #+END_SRC

  This fetches the kernel sources if necessary, runs bindgen, and
  splices its output into the `bindings` module's source code,
  preserving the documentation.
- [ ] ~cargo test --workspace~
- [ ] Look at the diff, and mention any `perf_event_open` API features
  that are now covered in ~perf-event-open-sys/RELEASE-NOTES.md~.
- [ ] Consider releasing a new version of the ~perf-event-open-sys~
  crate; see checklist above.
